### ISSUE TITLE
GitHub Action - roave-bc-check-ga missing exts but regular docker is not?

### ISSUE THREAD

**Issue by asgrim** [Nyholm/roave-bc-check-docker#19]
Possibly related to #18

I have a project that requires `ext-sockets` (among other extensions)

```
docker run --rm -v `pwd`:/app nyholm/roave-bc-check
```

Running this on my local machine works fine (yay)

However I added:

```
  roave-backwards-compatibility-check:
    name: "Check for BC breaks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Roave BC Check
        uses: docker://nyholm/roave-bc-check-ga
```

to my GH Actions, which fails, saying 

```
composer install --no-scripts --no-progress
  Installing dependencies from lock file (including require-dev)
  Verifying lock file contents can be installed on current platform.
  Your lock file does not contain a compatible set of packages. Please run composer update.
  
    Problem 1
      - Root composer.json requires PHP extension ext-sockets * but it is missing from your system. Install or enable PHP's sockets extension.
  
  To enable extensions, verify that they are enabled in your .ini files:
      - 
      - /usr/local/etc/php/conf.d/99_memory-limit.ini
      - /usr/local/etc/php/conf.d/docker-php-ext-bcmath.ini
      - /usr/local/etc/php/conf.d/docker-php-ext-gmp.ini
      - /usr/local/etc/php/conf.d/docker-php-ext-intl.ini
      - /usr/local/etc/php/conf.d/docker-php-ext-pcntl.ini
      - /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
```

What is the best approach to ensuring extensions are added here? Does the `nyholm/roave-bc-check-ga` image just need "all the extensions (TM)" or is there a way of saying which exts we want?
